#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResortinfo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="travel_db")]
	public partial class databaselinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmenu(menu instance);
    partial void Updatemenu(menu instance);
    partial void Deletemenu(menu instance);
    partial void Insertsitename(sitename instance);
    partial void Updatesitename(sitename instance);
    partial void Deletesitename(sitename instance);
    partial void Insertsoption(soption instance);
    partial void Updatesoption(soption instance);
    partial void Deletesoption(soption instance);
    partial void Insertgallerylist(gallerylist instance);
    partial void Updategallerylist(gallerylist instance);
    partial void Deletegallerylist(gallerylist instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertcomment(comment instance);
    partial void Updatecomment(comment instance);
    partial void Deletecomment(comment instance);
    partial void Insertpost(post instance);
    partial void Updatepost(post instance);
    partial void Deletepost(post instance);
    partial void Insertgallery(gallery instance);
    partial void Updategallery(gallery instance);
    partial void Deletegallery(gallery instance);
    #endregion
		
		public databaselinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["travel_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public databaselinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaselinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaselinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaselinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<menu> menus
		{
			get
			{
				return this.GetTable<menu>();
			}
		}
		
		public System.Data.Linq.Table<sitename> sitenames
		{
			get
			{
				return this.GetTable<sitename>();
			}
		}
		
		public System.Data.Linq.Table<soption> soptions
		{
			get
			{
				return this.GetTable<soption>();
			}
		}
		
		public System.Data.Linq.Table<gallerylist> gallerylists
		{
			get
			{
				return this.GetTable<gallerylist>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<view_alluser> view_allusers
		{
			get
			{
				return this.GetTable<view_alluser>();
			}
		}
		
		public System.Data.Linq.Table<comment> comments
		{
			get
			{
				return this.GetTable<comment>();
			}
		}
		
		public System.Data.Linq.Table<viewcomment> viewcomments
		{
			get
			{
				return this.GetTable<viewcomment>();
			}
		}
		
		public System.Data.Linq.Table<post> posts
		{
			get
			{
				return this.GetTable<post>();
			}
		}
		
		public System.Data.Linq.Table<view_post> view_posts
		{
			get
			{
				return this.GetTable<view_post>();
			}
		}
		
		public System.Data.Linq.Table<gallery> galleries
		{
			get
			{
				return this.GetTable<gallery>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_commentpinding", IsComposable=true)]
		public System.Nullable<int> f_commentpinding([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> c_status)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), c_status).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_countcomment", IsComposable=true)]
		public System.Nullable<int> f_countcomment([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pst_ID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pst_ID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_emailExist", IsComposable=true)]
		public System.Nullable<bool> f_emailExist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_login", IsComposable=true)]
		public System.Nullable<bool> f_login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_passwordExist", IsComposable=true)]
		public System.Nullable<bool> f_passwordExist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), password).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_posttitleExist", IsComposable=true)]
		public System.Nullable<bool> f_posttitleExist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pst_title)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pst_title).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_usernameExist", IsComposable=true)]
		public System.Nullable<bool> f_usernameExist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_userpostExist", IsComposable=true)]
		public System.Nullable<bool> f_userpostExist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_delete_tbl_comment")]
		public int sp_delete_tbl_comment([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pst_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pst_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_delete_post")]
		public int sp_delete_post([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pst_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pst_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_select_view_post")]
		public ISingleResult<sp_select_view_postResult> sp_select_view_post()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_select_view_postResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UPDATE_tbl_user")]
		public int sp_UPDATE_tbl_user([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string website, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, password, fname, lname, email, gender, website, date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_searchpost")]
		public ISingleResult<sp_searchpostResult> sp_searchpost([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pst_search)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pst_search);
			return ((ISingleResult<sp_searchpostResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_APPEND_tbl_post")]
		public int sp_APPEND_tbl_post([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pst_title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string pst_content, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> category, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string filename)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pst_title, pst_content, status, category, dte, user_id, filename);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UPDATE_tbl_post")]
		public int sp_UPDATE_tbl_post([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pst_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pst_title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string pst_content, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> category, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string filename)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pst_id, pst_title, pst_content, status, category, dte, user_id, filename);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_category_search")]
		public ISingleResult<sp_category_searchResult> sp_category_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_category_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_delete_usercomment")]
		public int sp_delete_usercomment([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UPDATE_tbl_gallery")]
		public int sp_UPDATE_tbl_gallery([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string filename, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pst_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, filename, date, user_id, pst_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UPDATE_tbl_gallerylist")]
		public int sp_UPDATE_tbl_gallerylist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gallery_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string filename, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string image)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gallery_id, filename, date, image);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_sAVE_tbl_gallerylist")]
		public int sp_sAVE_tbl_gallerylist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gallery_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string filename, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string image)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gallery_id, filename, date, image);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_newpost")]
		public ISingleResult<sp_newpostResult> sp_newpost()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_newpostResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_gallerysave")]
		public int sp_gallerysave([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string filename, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pst_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, filename, date, user_id, pst_id);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_menu")]
	public partial class menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _menu_id;
		
		private string _menu_name;
		
		private string _alias;
		
		private System.Nullable<int> _parent_id;
		
		private System.Nullable<int> _menu_perms;
		
		private System.Nullable<int> _menu_type;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<int> _m_view;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmenu_idChanging(int value);
    partial void Onmenu_idChanged();
    partial void Onmenu_nameChanging(string value);
    partial void Onmenu_nameChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    partial void Onparent_idChanging(System.Nullable<int> value);
    partial void Onparent_idChanged();
    partial void Onmenu_permsChanging(System.Nullable<int> value);
    partial void Onmenu_permsChanged();
    partial void Onmenu_typeChanging(System.Nullable<int> value);
    partial void Onmenu_typeChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Onm_viewChanging(System.Nullable<int> value);
    partial void Onm_viewChanged();
    #endregion
		
		public menu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int menu_id
		{
			get
			{
				return this._menu_id;
			}
			set
			{
				if ((this._menu_id != value))
				{
					this.Onmenu_idChanging(value);
					this.SendPropertyChanging();
					this._menu_id = value;
					this.SendPropertyChanged("menu_id");
					this.Onmenu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_name", DbType="NVarChar(50)")]
		public string menu_name
		{
			get
			{
				return this._menu_name;
			}
			set
			{
				if ((this._menu_name != value))
				{
					this.Onmenu_nameChanging(value);
					this.SendPropertyChanging();
					this._menu_name = value;
					this.SendPropertyChanged("menu_name");
					this.Onmenu_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="NVarChar(50)")]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="Int")]
		public System.Nullable<int> parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this.Onparent_idChanging(value);
					this.SendPropertyChanging();
					this._parent_id = value;
					this.SendPropertyChanged("parent_id");
					this.Onparent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_perms", DbType="Int")]
		public System.Nullable<int> menu_perms
		{
			get
			{
				return this._menu_perms;
			}
			set
			{
				if ((this._menu_perms != value))
				{
					this.Onmenu_permsChanging(value);
					this.SendPropertyChanging();
					this._menu_perms = value;
					this.SendPropertyChanged("menu_perms");
					this.Onmenu_permsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_type", DbType="Int")]
		public System.Nullable<int> menu_type
		{
			get
			{
				return this._menu_type;
			}
			set
			{
				if ((this._menu_type != value))
				{
					this.Onmenu_typeChanging(value);
					this.SendPropertyChanging();
					this._menu_type = value;
					this.SendPropertyChanged("menu_type");
					this.Onmenu_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_view", DbType="Int")]
		public System.Nullable<int> m_view
		{
			get
			{
				return this._m_view;
			}
			set
			{
				if ((this._m_view != value))
				{
					this.Onm_viewChanging(value);
					this.SendPropertyChanging();
					this._m_view = value;
					this.SendPropertyChanged("m_view");
					this.Onm_viewChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sitename")]
	public partial class sitename : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _disc;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _author;
		
		private string _email;
		
		private string _faq;
		
		private string _tagline;
		
		private string _about;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndiscChanging(string value);
    partial void OndiscChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnauthorChanging(string value);
    partial void OnauthorChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfaqChanging(string value);
    partial void OnfaqChanged();
    partial void OntaglineChanging(string value);
    partial void OntaglineChanged();
    partial void OnaboutChanging(string value);
    partial void OnaboutChanged();
    #endregion
		
		public sitename()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disc", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string disc
		{
			get
			{
				return this._disc;
			}
			set
			{
				if ((this._disc != value))
				{
					this.OndiscChanging(value);
					this.SendPropertyChanging();
					this._disc = value;
					this.SendPropertyChanged("disc");
					this.OndiscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="NVarChar(50)")]
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this.OnauthorChanging(value);
					this.SendPropertyChanging();
					this._author = value;
					this.SendPropertyChanged("author");
					this.OnauthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faq", DbType="NVarChar(MAX)")]
		public string faq
		{
			get
			{
				return this._faq;
			}
			set
			{
				if ((this._faq != value))
				{
					this.OnfaqChanging(value);
					this.SendPropertyChanging();
					this._faq = value;
					this.SendPropertyChanged("faq");
					this.OnfaqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tagline", DbType="NVarChar(50)")]
		public string tagline
		{
			get
			{
				return this._tagline;
			}
			set
			{
				if ((this._tagline != value))
				{
					this.OntaglineChanging(value);
					this.SendPropertyChanging();
					this._tagline = value;
					this.SendPropertyChanged("tagline");
					this.OntaglineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_about", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string about
		{
			get
			{
				return this._about;
			}
			set
			{
				if ((this._about != value))
				{
					this.OnaboutChanging(value);
					this.SendPropertyChanging();
					this._about = value;
					this.SendPropertyChanged("about");
					this.OnaboutChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_soption")]
	public partial class soption : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _disc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndiscChanging(string value);
    partial void OndiscChanged();
    #endregion
		
		public soption()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disc", DbType="NVarChar(50)")]
		public string disc
		{
			get
			{
				return this._disc;
			}
			set
			{
				if ((this._disc != value))
				{
					this.OndiscChanging(value);
					this.SendPropertyChanging();
					this._disc = value;
					this.SendPropertyChanged("disc");
					this.OndiscChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_gallerylist")]
	public partial class gallerylist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _gallery_id;
		
		private string _filename;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ongallery_idChanging(int value);
    partial void Ongallery_idChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    #endregion
		
		public gallerylist()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gallery_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int gallery_id
		{
			get
			{
				return this._gallery_id;
			}
			set
			{
				if ((this._gallery_id != value))
				{
					this.Ongallery_idChanging(value);
					this.SendPropertyChanging();
					this._gallery_id = value;
					this.SendPropertyChanged("gallery_id");
					this.Ongallery_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_user")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private string _fname;
		
		private string _lname;
		
		private string _email;
		
		private System.Nullable<int> _actype;
		
		private System.Nullable<int> _perms;
		
		private string _mname;
		
		private string _address;
		
		private string _image;
		
		private string _website;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _gender;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnactypeChanging(System.Nullable<int> value);
    partial void OnactypeChanged();
    partial void OnpermsChanging(System.Nullable<int> value);
    partial void OnpermsChanged();
    partial void OnmnameChanging(string value);
    partial void OnmnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OngenderChanging(System.Nullable<int> value);
    partial void OngenderChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="NVarChar(50)")]
		public string fname
		{
			get
			{
				return this._fname;
			}
			set
			{
				if ((this._fname != value))
				{
					this.OnfnameChanging(value);
					this.SendPropertyChanging();
					this._fname = value;
					this.SendPropertyChanged("fname");
					this.OnfnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="NVarChar(50)")]
		public string lname
		{
			get
			{
				return this._lname;
			}
			set
			{
				if ((this._lname != value))
				{
					this.OnlnameChanging(value);
					this.SendPropertyChanging();
					this._lname = value;
					this.SendPropertyChanged("lname");
					this.OnlnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actype", DbType="Int")]
		public System.Nullable<int> actype
		{
			get
			{
				return this._actype;
			}
			set
			{
				if ((this._actype != value))
				{
					this.OnactypeChanging(value);
					this.SendPropertyChanging();
					this._actype = value;
					this.SendPropertyChanged("actype");
					this.OnactypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perms", DbType="Int")]
		public System.Nullable<int> perms
		{
			get
			{
				return this._perms;
			}
			set
			{
				if ((this._perms != value))
				{
					this.OnpermsChanging(value);
					this.SendPropertyChanging();
					this._perms = value;
					this.SendPropertyChanged("perms");
					this.OnpermsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mname", DbType="NVarChar(50)")]
		public string mname
		{
			get
			{
				return this._mname;
			}
			set
			{
				if ((this._mname != value))
				{
					this.OnmnameChanging(value);
					this.SendPropertyChanging();
					this._mname = value;
					this.SendPropertyChanged("mname");
					this.OnmnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="NVarChar(50)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this.OnwebsiteChanging(value);
					this.SendPropertyChanging();
					this._website = value;
					this.SendPropertyChanged("website");
					this.OnwebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Int")]
		public System.Nullable<int> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_alluser")]
	public partial class view_alluser
	{
		
		private string _username;
		
		private string _fname;
		
		private string _lname;
		
		private string _email;
		
		private string _type;
		
		private string _address;
		
		private string _Permision;
		
		private string _gender;
		
		private string _mname;
		
		private int _id;
		
		private string _image;
		
		private string _website;
		
		private System.Nullable<System.DateTime> _date;
		
		public view_alluser()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="NVarChar(50)")]
		public string fname
		{
			get
			{
				return this._fname;
			}
			set
			{
				if ((this._fname != value))
				{
					this._fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="NVarChar(50)")]
		public string lname
		{
			get
			{
				return this._lname;
			}
			set
			{
				if ((this._lname != value))
				{
					this._lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permision", DbType="NVarChar(50)")]
		public string Permision
		{
			get
			{
				return this._Permision;
			}
			set
			{
				if ((this._Permision != value))
				{
					this._Permision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(50)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mname", DbType="NVarChar(50)")]
		public string mname
		{
			get
			{
				return this._mname;
			}
			set
			{
				if ((this._mname != value))
				{
					this._mname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this._image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="NVarChar(50)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this._website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_comment")]
	public partial class comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _c_ID;
		
		private int _pst_id;
		
		private string _c_content;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _c_email;
		
		private string _c_ip;
		
		private System.Nullable<int> _c_status;
		
		private System.Nullable<int> _user_id;
		
		private string _name;
		
		private string _website;
		
		private string _profilepic;
		
		private EntityRef<post> _post;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onc_IDChanging(int value);
    partial void Onc_IDChanged();
    partial void Onpst_idChanging(int value);
    partial void Onpst_idChanged();
    partial void Onc_contentChanging(string value);
    partial void Onc_contentChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void Onc_emailChanging(string value);
    partial void Onc_emailChanged();
    partial void Onc_ipChanging(string value);
    partial void Onc_ipChanged();
    partial void Onc_statusChanging(System.Nullable<int> value);
    partial void Onc_statusChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void OnprofilepicChanging(string value);
    partial void OnprofilepicChanged();
    #endregion
		
		public comment()
		{
			this._post = default(EntityRef<post>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int c_ID
		{
			get
			{
				return this._c_ID;
			}
			set
			{
				if ((this._c_ID != value))
				{
					this.Onc_IDChanging(value);
					this.SendPropertyChanging();
					this._c_ID = value;
					this.SendPropertyChanged("c_ID");
					this.Onc_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pst_id
		{
			get
			{
				return this._pst_id;
			}
			set
			{
				if ((this._pst_id != value))
				{
					if (this._post.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpst_idChanging(value);
					this.SendPropertyChanging();
					this._pst_id = value;
					this.SendPropertyChanged("pst_id");
					this.Onpst_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string c_content
		{
			get
			{
				return this._c_content;
			}
			set
			{
				if ((this._c_content != value))
				{
					this.Onc_contentChanging(value);
					this.SendPropertyChanging();
					this._c_content = value;
					this.SendPropertyChanged("c_content");
					this.Onc_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_email", DbType="NVarChar(50)")]
		public string c_email
		{
			get
			{
				return this._c_email;
			}
			set
			{
				if ((this._c_email != value))
				{
					this.Onc_emailChanging(value);
					this.SendPropertyChanging();
					this._c_email = value;
					this.SendPropertyChanged("c_email");
					this.Onc_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_ip", DbType="NVarChar(50)")]
		public string c_ip
		{
			get
			{
				return this._c_ip;
			}
			set
			{
				if ((this._c_ip != value))
				{
					this.Onc_ipChanging(value);
					this.SendPropertyChanging();
					this._c_ip = value;
					this.SendPropertyChanged("c_ip");
					this.Onc_ipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_status", DbType="Int")]
		public System.Nullable<int> c_status
		{
			get
			{
				return this._c_status;
			}
			set
			{
				if ((this._c_status != value))
				{
					this.Onc_statusChanging(value);
					this.SendPropertyChanging();
					this._c_status = value;
					this.SendPropertyChanged("c_status");
					this.Onc_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="NVarChar(50)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this.OnwebsiteChanging(value);
					this.SendPropertyChanging();
					this._website = value;
					this.SendPropertyChanged("website");
					this.OnwebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profilepic", DbType="NVarChar(50)")]
		public string profilepic
		{
			get
			{
				return this._profilepic;
			}
			set
			{
				if ((this._profilepic != value))
				{
					this.OnprofilepicChanging(value);
					this.SendPropertyChanging();
					this._profilepic = value;
					this.SendPropertyChanged("profilepic");
					this.OnprofilepicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="post_comment", Storage="_post", ThisKey="pst_id", OtherKey="pst_id", IsForeignKey=true)]
		public post post
		{
			get
			{
				return this._post.Entity;
			}
			set
			{
				post previousValue = this._post.Entity;
				if (((previousValue != value) 
							|| (this._post.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._post.Entity = null;
						previousValue.comments.Remove(this);
					}
					this._post.Entity = value;
					if ((value != null))
					{
						value.comments.Add(this);
						this._pst_id = value.pst_id;
					}
					else
					{
						this._pst_id = default(int);
					}
					this.SendPropertyChanged("post");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewcomment")]
	public partial class viewcomment
	{
		
		private int _c_ID;
		
		private string _c_content;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _c_email;
		
		private string _c_ip;
		
		private System.Nullable<int> _comment_count;
		
		private string _post_title;
		
		private string _c_status;
		
		private string _Username;
		
		private string _Userimage;
		
		private System.Nullable<int> _user_id;
		
		private int _pst_id;
		
		private string _name;
		
		private string _profilepic;
		
		public viewcomment()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_ID", DbType="Int NOT NULL")]
		public int c_ID
		{
			get
			{
				return this._c_ID;
			}
			set
			{
				if ((this._c_ID != value))
				{
					this._c_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string c_content
		{
			get
			{
				return this._c_content;
			}
			set
			{
				if ((this._c_content != value))
				{
					this._c_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_email", DbType="NVarChar(50)")]
		public string c_email
		{
			get
			{
				return this._c_email;
			}
			set
			{
				if ((this._c_email != value))
				{
					this._c_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_ip", DbType="NVarChar(50)")]
		public string c_ip
		{
			get
			{
				return this._c_ip;
			}
			set
			{
				if ((this._c_ip != value))
				{
					this._c_ip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment_count", DbType="Int")]
		public System.Nullable<int> comment_count
		{
			get
			{
				return this._comment_count;
			}
			set
			{
				if ((this._comment_count != value))
				{
					this._comment_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_title", DbType="NVarChar(50)")]
		public string post_title
		{
			get
			{
				return this._post_title;
			}
			set
			{
				if ((this._post_title != value))
				{
					this._post_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_status", DbType="NVarChar(50)")]
		public string c_status
		{
			get
			{
				return this._c_status;
			}
			set
			{
				if ((this._c_status != value))
				{
					this._c_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Userimage", DbType="NVarChar(50)")]
		public string Userimage
		{
			get
			{
				return this._Userimage;
			}
			set
			{
				if ((this._Userimage != value))
				{
					this._Userimage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_id", DbType="Int NOT NULL")]
		public int pst_id
		{
			get
			{
				return this._pst_id;
			}
			set
			{
				if ((this._pst_id != value))
				{
					this._pst_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profilepic", DbType="NVarChar(50)")]
		public string profilepic
		{
			get
			{
				return this._profilepic;
			}
			set
			{
				if ((this._profilepic != value))
				{
					this._profilepic = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_post")]
	public partial class post : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pst_id;
		
		private string _pst_title;
		
		private string _pst_content;
		
		private string _ip;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _dte;
		
		private System.Nullable<int> _user_id;
		
		private string _filename;
		
		private System.Nullable<int> _category;
		
		private EntitySet<comment> _comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpst_idChanging(int value);
    partial void Onpst_idChanged();
    partial void Onpst_titleChanging(string value);
    partial void Onpst_titleChanged();
    partial void Onpst_contentChanging(string value);
    partial void Onpst_contentChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OndteChanging(System.Nullable<System.DateTime> value);
    partial void OndteChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void OncategoryChanging(System.Nullable<int> value);
    partial void OncategoryChanged();
    #endregion
		
		public post()
		{
			this._comments = new EntitySet<comment>(new Action<comment>(this.attach_comments), new Action<comment>(this.detach_comments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pst_id
		{
			get
			{
				return this._pst_id;
			}
			set
			{
				if ((this._pst_id != value))
				{
					this.Onpst_idChanging(value);
					this.SendPropertyChanging();
					this._pst_id = value;
					this.SendPropertyChanged("pst_id");
					this.Onpst_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_title", DbType="NVarChar(50)")]
		public string pst_title
		{
			get
			{
				return this._pst_title;
			}
			set
			{
				if ((this._pst_title != value))
				{
					this.Onpst_titleChanging(value);
					this.SendPropertyChanging();
					this._pst_title = value;
					this.SendPropertyChanged("pst_title");
					this.Onpst_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string pst_content
		{
			get
			{
				return this._pst_content;
			}
			set
			{
				if ((this._pst_content != value))
				{
					this.Onpst_contentChanging(value);
					this.SendPropertyChanging();
					this._pst_content = value;
					this.SendPropertyChanged("pst_content");
					this.Onpst_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="NVarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dte", DbType="DateTime")]
		public System.Nullable<System.DateTime> dte
		{
			get
			{
				return this._dte;
			}
			set
			{
				if ((this._dte != value))
				{
					this.OndteChanging(value);
					this.SendPropertyChanging();
					this._dte = value;
					this.SendPropertyChanged("dte");
					this.OndteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(50)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="Int")]
		public System.Nullable<int> category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="post_comment", Storage="_comments", ThisKey="pst_id", OtherKey="pst_id")]
		public EntitySet<comment> comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				this._comments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_comments(comment entity)
		{
			this.SendPropertyChanging();
			entity.post = this;
		}
		
		private void detach_comments(comment entity)
		{
			this.SendPropertyChanging();
			entity.post = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_post")]
	public partial class view_post
	{
		
		private int _pst_id;
		
		private string _pst_title;
		
		private string _pst_content;
		
		private string _ip;
		
		private string _status;
		
		private System.Nullable<int> _category;
		
		private System.Nullable<System.DateTime> _dte;
		
		private System.Nullable<int> _user_id;
		
		private string _filename;
		
		private System.Nullable<int> _comment_count;
		
		private string _Username;
		
		private string _Userimage;
		
		public view_post()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int pst_id
		{
			get
			{
				return this._pst_id;
			}
			set
			{
				if ((this._pst_id != value))
				{
					this._pst_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_title", DbType="NVarChar(50)")]
		public string pst_title
		{
			get
			{
				return this._pst_title;
			}
			set
			{
				if ((this._pst_title != value))
				{
					this._pst_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string pst_content
		{
			get
			{
				return this._pst_content;
			}
			set
			{
				if ((this._pst_content != value))
				{
					this._pst_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="NVarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this._ip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="Int")]
		public System.Nullable<int> category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dte", DbType="DateTime")]
		public System.Nullable<System.DateTime> dte
		{
			get
			{
				return this._dte;
			}
			set
			{
				if ((this._dte != value))
				{
					this._dte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(50)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this._filename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment_count", DbType="Int")]
		public System.Nullable<int> comment_count
		{
			get
			{
				return this._comment_count;
			}
			set
			{
				if ((this._comment_count != value))
				{
					this._comment_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Userimage", DbType="NVarChar(50)")]
		public string Userimage
		{
			get
			{
				return this._Userimage;
			}
			set
			{
				if ((this._Userimage != value))
				{
					this._Userimage = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_gallery")]
	public partial class gallery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gallery_id;
		
		private string _title;
		
		private string _filename;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _user_id;
		
		private System.Nullable<int> _pst_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongallery_idChanging(int value);
    partial void Ongallery_idChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onpst_idChanging(System.Nullable<int> value);
    partial void Onpst_idChanged();
    #endregion
		
		public gallery()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gallery_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int gallery_id
		{
			get
			{
				return this._gallery_id;
			}
			set
			{
				if ((this._gallery_id != value))
				{
					this.Ongallery_idChanging(value);
					this.SendPropertyChanging();
					this._gallery_id = value;
					this.SendPropertyChanged("gallery_id");
					this.Ongallery_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_id", DbType="Int")]
		public System.Nullable<int> pst_id
		{
			get
			{
				return this._pst_id;
			}
			set
			{
				if ((this._pst_id != value))
				{
					this.Onpst_idChanging(value);
					this.SendPropertyChanging();
					this._pst_id = value;
					this.SendPropertyChanged("pst_id");
					this.Onpst_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_select_view_postResult
	{
		
		private string _pst_title;
		
		private int _pst_id;
		
		public sp_select_view_postResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_title", DbType="NVarChar(50)")]
		public string pst_title
		{
			get
			{
				return this._pst_title;
			}
			set
			{
				if ((this._pst_title != value))
				{
					this._pst_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_id", DbType="Int NOT NULL")]
		public int pst_id
		{
			get
			{
				return this._pst_id;
			}
			set
			{
				if ((this._pst_id != value))
				{
					this._pst_id = value;
				}
			}
		}
	}
	
	public partial class sp_searchpostResult
	{
		
		private string _pst_title;
		
		private string _pst_content;
		
		private System.Nullable<System.DateTime> _dte;
		
		private System.Nullable<int> _user_id;
		
		private System.Nullable<int> _comment_count;
		
		private int _pst_id;
		
		private string _category;
		
		private string _Username;
		
		private string _filename;
		
		public sp_searchpostResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_title", DbType="NVarChar(50)")]
		public string pst_title
		{
			get
			{
				return this._pst_title;
			}
			set
			{
				if ((this._pst_title != value))
				{
					this._pst_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string pst_content
		{
			get
			{
				return this._pst_content;
			}
			set
			{
				if ((this._pst_content != value))
				{
					this._pst_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dte", DbType="DateTime")]
		public System.Nullable<System.DateTime> dte
		{
			get
			{
				return this._dte;
			}
			set
			{
				if ((this._dte != value))
				{
					this._dte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment_count", DbType="Int")]
		public System.Nullable<int> comment_count
		{
			get
			{
				return this._comment_count;
			}
			set
			{
				if ((this._comment_count != value))
				{
					this._comment_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_id", DbType="Int NOT NULL")]
		public int pst_id
		{
			get
			{
				return this._pst_id;
			}
			set
			{
				if ((this._pst_id != value))
				{
					this._pst_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(50)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this._filename = value;
				}
			}
		}
	}
	
	public partial class sp_category_searchResult
	{
		
		private string _pst_title;
		
		private string _pst_content;
		
		private System.Nullable<System.DateTime> _dte;
		
		private System.Nullable<int> _comment_count;
		
		private int _pst_id;
		
		private System.Nullable<int> _category;
		
		private string _Username;
		
		private System.Nullable<int> _user_id;
		
		private string _filename;
		
		public sp_category_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_title", DbType="NVarChar(50)")]
		public string pst_title
		{
			get
			{
				return this._pst_title;
			}
			set
			{
				if ((this._pst_title != value))
				{
					this._pst_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string pst_content
		{
			get
			{
				return this._pst_content;
			}
			set
			{
				if ((this._pst_content != value))
				{
					this._pst_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dte", DbType="DateTime")]
		public System.Nullable<System.DateTime> dte
		{
			get
			{
				return this._dte;
			}
			set
			{
				if ((this._dte != value))
				{
					this._dte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment_count", DbType="Int")]
		public System.Nullable<int> comment_count
		{
			get
			{
				return this._comment_count;
			}
			set
			{
				if ((this._comment_count != value))
				{
					this._comment_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_id", DbType="Int NOT NULL")]
		public int pst_id
		{
			get
			{
				return this._pst_id;
			}
			set
			{
				if ((this._pst_id != value))
				{
					this._pst_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="Int")]
		public System.Nullable<int> category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(50)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this._filename = value;
				}
			}
		}
	}
	
	public partial class sp_newpostResult
	{
		
		private string _pst_title;
		
		private int _pst_id;
		
		public sp_newpostResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_title", DbType="NVarChar(50)")]
		public string pst_title
		{
			get
			{
				return this._pst_title;
			}
			set
			{
				if ((this._pst_title != value))
				{
					this._pst_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pst_id", DbType="Int NOT NULL")]
		public int pst_id
		{
			get
			{
				return this._pst_id;
			}
			set
			{
				if ((this._pst_id != value))
				{
					this._pst_id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
