<?xml version="1.0" encoding="utf-8"?><Database Name="travel_db" Class="databaselinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=GONZALES-PC\SQLEXPRESS;Initial Catalog=travel_db;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="travel_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_menu" Member="menus">
    <Type Name="menu">
      <Column Name="menu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="menu_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="alias" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="menu_perms" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="menu_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="m_view" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_sitename" Member="sitenames">
    <Type Name="sitename">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="disc" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="author" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="faq" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tagline" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="about" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_soption" Member="soptions">
    <Type Name="soption">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="disc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_gallerylist" Member="gallerylists">
    <Type Name="gallerylist">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gallery_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="filename" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_user" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="actype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="perms" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_alluser" Member="view_allusers">
    <Type Name="view_alluser">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Permision" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_comment" Member="comments">
    <Type Name="comment">
      <Column Name="c_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pst_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="c_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="c_email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="c_ip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="c_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="profilepic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="post_comment" Member="post" ThisKey="pst_id" OtherKey="pst_id" Type="post" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.viewcomment" Member="viewcomments">
    <Type Name="viewcomment">
      <Column Name="c_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="c_email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="c_ip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="comment_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="post_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="c_status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Userimage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pst_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="profilepic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_post" Member="posts">
    <Type Name="post">
      <Column Name="pst_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pst_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pst_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dte" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="filename" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="post_comment" Member="comments" ThisKey="pst_id" OtherKey="pst_id" Type="comment" />
    </Type>
  </Table>
  <Table Name="dbo.view_post" Member="view_posts">
    <Type Name="view_post">
      <Column Name="pst_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pst_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pst_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dte" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="filename" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="comment_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Userimage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_gallery" Member="galleries">
    <Type Name="gallery">
      <Column Name="gallery_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="filename" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pst_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.f_commentpinding" Method="f_commentpinding" IsComposable="true">
    <Parameter Name="c_status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.f_countcomment" Method="f_countcomment" IsComposable="true">
    <Parameter Name="pst_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.f_emailExist" Method="f_emailExist" IsComposable="true">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.f_login" Method="f_login" IsComposable="true">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.f_passwordExist" Method="f_passwordExist" IsComposable="true">
    <Parameter Name="password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.f_posttitleExist" Method="f_posttitleExist" IsComposable="true">
    <Parameter Name="pst_title" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.f_usernameExist" Method="f_usernameExist" IsComposable="true">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.f_userpostExist" Method="f_userpostExist" IsComposable="true">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.sp_delete_tbl_comment" Method="sp_delete_tbl_comment">
    <Parameter Name="pst_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_delete_post" Method="sp_delete_post">
    <Parameter Name="pst_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_select_view_post" Method="sp_select_view_post">
    <ElementType Name="sp_select_view_postResult">
      <Column Name="pst_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pst_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UPDATE_tbl_user" Method="sp_UPDATE_tbl_user">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="fname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="lname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="website" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_searchpost" Method="sp_searchpost">
    <Parameter Name="pst_search" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_searchpostResult">
      <Column Name="pst_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pst_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dte" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pst_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="filename" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_APPEND_tbl_post" Method="sp_APPEND_tbl_post">
    <Parameter Name="pst_title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pst_content" Type="System.String" DbType="Text" />
    <Parameter Name="status" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="category" Type="System.Int32" DbType="Int" />
    <Parameter Name="dte" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="filename" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UPDATE_tbl_post" Method="sp_UPDATE_tbl_post">
    <Parameter Name="pst_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pst_title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pst_content" Type="System.String" DbType="Text" />
    <Parameter Name="status" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="category" Type="System.Int32" DbType="Int" />
    <Parameter Name="dte" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="filename" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_category_search" Method="sp_category_search">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_category_searchResult">
      <Column Name="pst_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pst_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dte" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="comment_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pst_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="filename" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_delete_usercomment" Method="sp_delete_usercomment">
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UPDATE_tbl_gallery" Method="sp_UPDATE_tbl_gallery">
    <Parameter Name="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="filename" Type="System.String" DbType="Text" />
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pst_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UPDATE_tbl_gallerylist" Method="sp_UPDATE_tbl_gallerylist">
    <Parameter Name="gallery_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="filename" Type="System.String" DbType="Text" />
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="image" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_sAVE_tbl_gallerylist" Method="sp_sAVE_tbl_gallerylist">
    <Parameter Name="gallery_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="filename" Type="System.String" DbType="Text" />
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="image" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_newpost" Method="sp_newpost">
    <ElementType Name="sp_newpostResult">
      <Column Name="pst_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pst_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_gallerysave" Method="sp_gallerysave">
    <Parameter Name="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="filename" Type="System.String" DbType="Text" />
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pst_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>